[tools]
node = "lts"
pnpm = "latest"
usage = "latest"
go = "latest"
"go:github.com/danielmiessler/fabric/cmd/fabric" = "latest"
"go:github.com/vekio/vek/cmd/vek" = { version = "latest", minimum_release_age = "0s" }
"npm:@openai/codex" = "latest"

[settings.npm]
package_manager = "pnpm"
