[tools]
node = "lts"
pnpm = "latest"
usage = "latest"
go = "latest"
"go:github.com/danielmiessler/fabric/cmd/fabric" = "latest"
"npm:@openai/codex" = "latest"

[settings.npm]
package_manager = "pnpm"
