# config files
# -----------------------------------------------------------------------------
[[ -f "${XDG_CONFIG_HOME}/zsh/.aliases" ]] && . "${XDG_CONFIG_HOME}/zsh/.aliases"
[[ -f "${XDG_CONFIG_HOME}/zsh/.fzf" ]] && . "${XDG_CONFIG_HOME}/zsh/.fzf"

# fzf
# --------------------------------------------------------------------
if [[ ! "${PATH}" == *${XDG_DATA_HOME}/fzf/bin* ]]; then
    export PATH="${PATH:+${PATH}:}${XDG_DATA_HOME}/fzf/bin"
fi
[[ $- == *i* ]] && . "${XDG_DATA_HOME}/fzf/shell/completion.zsh" 2> /dev/null
. "${XDG_DATA_HOME}/fzf/shell/key-bindings.zsh"

# nvm
# -----------------------------------------------------------------------------
export NVM_DIR="$([[ -z "${XDG_CONFIG_HOME-}" ]] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[[ -s "${NVM_DIR}/nvm.sh" ]] && \. "${NVM_DIR}/nvm.sh"

# starship
# -----------------------------------------------------------------------------
[[ -f "${HOME}/.local/bin/starship" ]] && eval "$(starship init zsh)"

# terraform
# -----------------------------------------------------------------------------
[[ -f "/usr/bin/terraform" ]] && complete -C /usr/bin/terraform terraform
